In [56]:
import numpy as np
import lxml.etree
import random
import pandas as pd


class Genetic:
    def __init__(self):
        self.universal_chrm = np.empty


    def get_feasible(self, chrm):
        values = []
        print("equation: 2x + 2y - 4z + 3w -8a +7b = 0") # 1 0 1 1 1 1
        for i in range(chrm.shape[0]):
            print("interation", i, chrm[i]) 
            values.append(2*(chrm[i][0]) + 2*(chrm[i][1]) - 4*(chrm[i][2]) + 3*(chrm[i][3]) -8*(chrm[i][4]) + 2*(chrm[i][5]))
        return values
        
    #1
    def initiate_genetic_generation(chrm): #it compares the chromosomes of current generation with the previous generation, returns the best chrm
        if len(universal_chrm) == 0:
                self.universal_chrm = chrm
        else:
                if get_feasible(self.universal_chrm) > get_feasible(chrm): #need the fitness score calculation for chromosome DOUBT about function
                        return self.universal_chrm
                else:
                        self.universal_chrm = chrm
        return chrm
    #2
    def crossover(self,parents,crossover_prob): #chrm acts as parents here
        chromosome_size = (parents.shape[1])
        row_size = parents.shape[0] #creating new generations parents -> offsprings
        offspring = np.copy(parents)
        print("Offprings are: ", '/n', offspring)
        
        selected_parents_indexes=np.random.choice(list(range(row_size)),int(crossover_prob*row_size),replace=False)
        print("indexes of selected parents", selected_parents_indexes)
        
        crossover_point = int(chromosome_size/2)
        
        for i in range(len(selected_parents_indexes)):
            if i!=len(selected_parents_indexes)-1:
                offspring[selected_parents_indexes[i]] = list(parents[selected_parents_indexes[i]]
                [:crossover_point]) + list(parents[selected_parents_indexes[i+1]]
                [:crossover_point-1:-1])
                
                #offspring = np.vstack((offspring, list(parents[selected_parents_indexes[i+1]][:crossover_point]) + list(parents[selected_parents_indexes[i]][:crossover_point-1:-1])))
        else:
                offspring[selected_parents_indexes[i]] = list(parents[selected_parents_indexes[i]]
                [:crossover_point]) + list(parents[selected_parents_indexes[0]]
                [:crossover_point-1:-1])
                
                #np.vstack((offspring, list(parents[selected_parents_indexes[i+1]][:crossover_point-1:-1]) + list(parents[selected_parents_indexes[i]][:crossover_point])))
                
        print('Offsprings from crossover: ','\n', offspring)
        return offspring



#step 5
    def mutation(self, chrm,mutation_prob):
        sampleList=np.random.choice(list(range(chrm.shape[0])),int(mutation_prob*chrm.shape[0]),replace=False)
        print(sampleList, type(sampleList))
        for i in range(chrm.shape[0]):
            for j in range(len(sampleList)): #edit
                chrm[i][j] = chrm[i][j]^1
        print("Chromosome after mutation: ", '\n', chrm)
        return chrm
    
    #step 6
    def selection(self,chrm,fitness_limit):
        dictionary = {}
        for i in chrm.shape[0]:
                dictionary.append(chrm[i], get_feasible(chrm[i]))#calculate fitness value of all the chomosomes from sample
        bestChromosomes_fitness_ascending=dict(sorted(dictionary.items(), key=lambda item: item[1]))  #sort from the dictionary top10 top8 top 12
        selectedChromosomes = roulette_wheel_spin(bestChromosomes_fitness_ascending, self.population_size) #selected best chromosome based on whee
        return selectedChromosomes



    def roulette_wheel_spin(self, bestChromosomes_fitness_ascending,population):
            max = sum([c.bestChromosomes_fitness_ascending for c in population])
            pick = random.uniform(0, max)
            current = 0
            for chromosome in population:
                current += chromosome.bestChromosomes_fitness_ascending
            if current > pick:
                return chromosome
        #these are chromosomes for next generation



chrm = np.random.randint(2, size=(4,6))
print(chrm)
#chrm = np.vstack((chrm,[1,2,1]))
print('---------------------------------')
g = Genetic()
print(g.get_feasible(chrm))
print('---------------------------------')
new_chrm = g.crossover(chrm, 0.5)
print('---------------------------------')

"""
print('rows', chrm.shape[0])
print('columns', chrm.shape[1])
print(chrm[2])

"""









[[1 1 0 0 0 1]
 [0 1 1 0 1 0]
 [1 1 1 0 0 1]
 [1 0 0 0 1 0]]
---------------------------------
equation: 2x + 2y - 4z + 3w -8a +7b = 0
interation 0 [1 1 0 0 0 1]
interation 1 [0 1 1 0 1 0]
interation 2 [1 1 1 0 0 1]
interation 3 [1 0 0 0 1 0]
[6, -10, 2, -6]
---------------------------------
Offprings are:  /n [[1 1 0 0 0 1]
 [0 1 1 0 1 0]
 [1 1 1 0 0 1]
 [1 0 0 0 1 0]]
indexes of selected parents [1 2]
Offsprings from crossover:  
 [[1 1 0 0 0 1]
 [0 1 1 1 0 0]
 [1 1 1 0 1 0]
 [1 0 0 0 1 0]]
---------------------------------


"\nprint('rows', chrm.shape[0])\nprint('columns', chrm.shape[1])\nprint(chrm[2])\n\n"

In [44]:
lame = [1,2,3]
for i in range(len(lame)):
    lame.append(i)
print(lame)

[1, 2, 3, 0, 1, 2]
